import type { Product } from "@/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Element Section Complete Skateboard",
    description: "Patineta completa profesional perfecta para principiantes y riders intermedios.",
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    image: "/element-skateboard-complete.png",
    category: "completas",
    brand: "element",
    rating: 5,
    reviews: 124,
    inStock: true,
    features: ["Maple canadiense 7 capas", "Trucks de aleación", "Ruedas PU 52mm"],
  },
  {
    id: "2",
    name: "Santa Cruz Classic Dot Deck",
    description: "Tabla clásica de Santa Cruz con diseño icónico y construcción premium.",
    price: 54.99,
    image: "/santa-cruz-deck.png",
    category: "tablas",
    brand: "santa-cruz",
    rating: 5,
    reviews: 89,
    inStock: true,
    features: ["Maple canadiense", "Concave medium", "Gráfico clásico"],
  },
  {
    id: "3",
    name: "Independent Stage 11 Trucks",
    description: "Trucks profesionales Independent con tecnología de última generación.",
    price: 64.99,
    image: "/independent-skateboard-trucks.png",
    category: "trucks",
    brand: "independent",
    rating: 5,
    reviews: 156,
    inStock: true,
    features: ["Aleación de aluminio", "Geometría Stage 11", "Bushings premium"],
  },
  {
    id: "4",
    name: "Bones Reds Bearings",
    description: "Rodamientos Bones Reds, los más populares del mundo del skateboarding.",
    price: 19.99,
    image: "/placeholder-2gtup.png",
    category: "rodamientos",
    brand: "bones",
    rating: 5,
    reviews: 234,
    inStock: true,
    features: ["ABEC-5", "Lubricación Speed Cream", "Set de 8 rodamientos"],
  },
  {
    id: "5",
    name: "Powell Peralta Dragon Formula Wheels",
    description: "Ruedas de alta calidad con fórmula Dragon para máximo rendimiento.",
    price: 39.99,
    image: "/placeholder-qpbsi.png",
    category: "ruedas",
    brand: "powell-peralta",
    rating: 4,
    reviews: 78,
    inStock: true,
    features: ["Fórmula Dragon", "56mm 93A", "Grip excepcional"],
  },
  {
    id: "6",
    name: "Element Nyjah Huston Pro Model",
    description: "Modelo pro de Nyjah Huston con gráfico exclusivo y specs profesionales.",
    price: 129.99,
    originalPrice: 149.99,
    discount: 13,
    image: "/skateboarder-in-motion.png",
    category: "completas",
    brand: "element",
    rating: 5,
    reviews: 67,
    inStock: true,
    features: ["Modelo pro", "Componentes premium", "Gráfico exclusivo"],
  },
  {
    id: "7",
    name: "Santa Cruz Screaming Hand Deck",
    description: "Icónica tabla Screaming Hand de Santa Cruz, un clásico atemporal.",
    price: 59.99,
    image: "/screaming-hand-skateboard-deck.png",
    category: "tablas",
    brand: "santa-cruz",
    rating: 5,
    reviews: 145,
    inStock: true,
    features: ["Diseño icónico", "Maple premium", "Múltiples tamaños"],
  },
  {
    id: "8",
    name: "Bones Swiss Bearings",
    description: "Los rodamientos más precisos de Bones, fabricados en Suiza.",
    price: 89.99,
    image: "/placeholder-m0z76.png",
    category: "rodamientos",
    brand: "bones",
    rating: 5,
    reviews: 198,
    inStock: true,
    features: ["Fabricados en Suiza", "Precisión máxima", "Durabilidad superior"],
  },
  {
    id: "9",
    name: "Element Grip Tape",
    description: "Lija de alta calidad Element con adhesivo duradero.",
    price: 9.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "accesorios",
    brand: "element",
    rating: 4,
    reviews: 89,
    inStock: true,
    features: ["Adhesivo fuerte", "Textura premium", "Fácil aplicación"],
  },
  {
    id: "10",
    name: "Independent Hardware Set",
    description: "Set completo de tornillos y tuercas Independent para tu setup.",
    price: 7.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "accesorios",
    brand: "independent",
    rating: 4,
    reviews: 45,
    inStock: true,
    features: ["Acero inoxidable", "Múltiples tamaños", "Resistente a la corrosión"],
  },
]
